### ISSUE TITLE
Remove Google+ and add link to Slack group

### ISSUE THREAD

**Issue by macdonst** [ottawajs/ottawajs.github.com#5]
I think the time for Google+ has come and gone. We should remove that from the how to get involved section and replace it with a link to the slack sign up.

**Comment by rjriel** [comment]
What's Google+?

Srsly tho, I agree.

**Comment by daneroo** [comment]
I'm on it.

**Comment by daneroo** [comment]
Done. e1c56cb0275f484a490c725cd97c5a5ee2730ba0

**Comment by macdonst** [comment]
Thanks Dan
